version: 2

project_name: etherscan

report_sizes: true

gomod:
  proxy: true

builds:
  - id: etherscan
    main: ./cmd/etherscan
    binary: etherscan
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    mod_timestamp: "{{ .CommitTimestamp }}"
    ldflags:
      - >-
        -s -w
        -X main.version={{ .Version }}
        -X main.commit={{ .Commit }}
        -X main.date={{ .CommitDate }}

archives:
  - id: etherscan
    ids:
      - etherscan
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    files:
      - README.md

checksum:
  name_template: checksums.txt

sboms:
  - id: archives
    artifacts: archive

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc

release:
  prerelease: auto
